# Generated by Django 5.1.2 on 2026-02-28 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('execution_mode', models.CharField(choices=[('base', 'Base'), ('stressed', 'Stressed'), ('dual', 'Dual (base + stressed)')], default='base', max_length=20)),
                ('initial_cash_usd', models.FloatField(default=10000.0)),
                ('cash_usd', models.FloatField(default=10000.0)),
                ('total_equity_usd', models.FloatField(default=10000.0)),
                ('high_water_mark_usd', models.FloatField(default=10000.0)),
                ('max_positions', models.IntegerField(default=10)),
                ('max_position_pct', models.FloatField(default=0.05, help_text='Max single position as fraction of equity')),
                ('base_risk_pct', models.FloatField(default=0.01, help_text='Base risk per trade as fraction of equity')),
                ('hard_abs_cap_usd', models.FloatField(default=500.0, help_text='Absolute max USD per trade')),
                ('max_holding_hours', models.IntegerField(default=168, help_text='Time stop: max hours to hold')),
                ('stop_loss_pct', models.FloatField(default=0.2, help_text='Price stop: max loss from entry')),
                ('take_profit_ladder', models.JSONField(blank=True, default=list, help_text='Take-profit levels, e.g. [{"pct": 0.50, "sell_fraction": 0.25}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_uid', models.CharField(db_index=True, max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('chain', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('written_off', 'Written Off')], db_index=True, default='open', max_length=20)),
                ('entry_price_usd', models.FloatField()),
                ('avg_entry_price_usd', models.FloatField()),
                ('quantity', models.FloatField()),
                ('cost_basis_usd', models.FloatField()),
                ('current_price_usd', models.FloatField(default=0.0)),
                ('current_value_usd', models.FloatField(default=0.0)),
                ('unrealized_pnl_usd', models.FloatField(default=0.0)),
                ('unrealized_pnl_pct', models.FloatField(default=0.0)),
                ('exit_price_usd', models.FloatField(blank=True, null=True)),
                ('realized_pnl_usd', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('token_address', models.CharField(blank=True, default='', max_length=200)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='paper_trading.paperportfolio')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_uid', models.CharField(db_index=True, max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('chain', models.CharField(max_length=30)),
                ('token_bucket', models.CharField(blank=True, default='', max_length=50)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('status', models.CharField(choices=[('filled', 'Filled'), ('rejected', 'Rejected')], default='filled', max_length=20)),
                ('requested_notional_usd', models.FloatField()),
                ('filled_notional_usd', models.FloatField(default=0.0)),
                ('filled_quantity', models.FloatField(default=0.0)),
                ('arrival_price_usd', models.FloatField()),
                ('executed_price_usd', models.FloatField(default=0.0)),
                ('slippage_bps', models.FloatField(default=0.0)),
                ('impact_bps', models.FloatField(default=0.0)),
                ('venue_fee_usd', models.FloatField(default=0.0)),
                ('tax_usd', models.FloatField(default=0.0)),
                ('gas_usd', models.FloatField(default=0.0)),
                ('total_cost_usd', models.FloatField(default=0.0)),
                ('failure_probability', models.FloatField(default=0.0)),
                ('liquidity_snapshot', models.JSONField(blank=True, default=dict, help_text='Pool liquidity data at fill time')),
                ('signal_context', models.JSONField(blank=True, default=dict, help_text='Signal that triggered this trade')),
                ('stressed_executed_price_usd', models.FloatField(blank=True, null=True)),
                ('stressed_impact_bps', models.FloatField(blank=True, null=True)),
                ('stressed_total_cost_usd', models.FloatField(blank=True, null=True)),
                ('stressed_failure_probability', models.FloatField(blank=True, null=True)),
                ('trigger_type', models.CharField(blank=True, db_index=True, default='', help_text='What triggered this trade (e.g. smart_money, score_jump)', max_length=50)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=300)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper_trading.paperportfolio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='paper_trading.paperposition')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperEquitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cash_usd', models.FloatField()),
                ('positions_value_usd', models.FloatField()),
                ('total_equity_usd', models.FloatField()),
                ('drawdown_pct', models.FloatField(default=0.0)),
                ('open_positions', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_snapshots', to='paper_trading.paperportfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['portfolio', '-timestamp'], name='paper_tradi_portfol_9d9819_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paperposition',
            index=models.Index(fields=['portfolio', 'status'], name='paper_tradi_portfol_a3db84_idx'),
        ),
        migrations.AddIndex(
            model_name='paperposition',
            index=models.Index(fields=['asset_uid', 'status'], name='paper_tradi_asset_u_f20c40_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['portfolio', '-executed_at'], name='paper_tradi_portfol_a8ca0d_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['trigger_type'], name='paper_tradi_trigger_56360c_idx'),
        ),
    ]
