# Generated by Django 5.1.2 on 2026-02-28 17:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regime', models.CharField(choices=[('mania', 'Mania'), ('rotation', 'Rotation'), ('flight_to_quality', 'Flight to Quality'), ('low_activity', 'Low Activity'), ('capitulation', 'Capitulation')], db_index=True, default='low_activity', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('scores', models.JSONField(default=dict, help_text='Score breakdown per regime')),
                ('aggregate_metrics', models.JSONField(default=dict, help_text='Aggregate watchlist metrics used for detection')),
                ('token_count', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
