# Generated by Django 5.1.2 on 2026-02-28 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFreshness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=100, unique=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('staleness_threshold_hours', models.IntegerField(default=36, help_text='Hours after which data is considered stale')),
            ],
            options={
                'verbose_name_plural': 'data freshness',
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', '-started_at'], name='api_taskrun_task_na_6ba66e_idx')],
            },
        ),
    ]
