# Generated by Django 5.1.2 on 2026-02-28 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('signal_state_change', 'Signal State Change'), ('threshold_breach', 'Threshold Breach'), ('anomaly', 'Anomaly Detection')], db_index=True, max_length=30)),
                ('card_key', models.CharField(db_index=True, help_text='Signal card key (e.g. trends, fng, onchain)', max_length=30)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Type-specific config. signal_state_change: {from_states, to_states}. threshold_breach: {metric, operator, value}. anomaly: {metric, window, sigma}.')),
                ('cooldown_minutes', models.PositiveIntegerField(default=1440, help_text='Minimum minutes between repeated firings of the same rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Snapshot of the metric values at evaluation time')),
                ('fired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.alertrule')),
            ],
            options={
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['rule', '-fired_at'], name='api_alertev_rule_id_34b1d1_idx')],
            },
        ),
    ]
