# Generated by Django 5.1.2 on 2026-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alertrule_alertevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('signal_state_change', 'Signal State Change'), ('threshold_breach', 'Threshold Breach'), ('anomaly', 'Anomaly Detection'), ('whale_accumulation', 'Whale Accumulation'), ('liquidity_event', 'Liquidity Event'), ('rug_risk_detected', 'Rug Risk Detected'), ('explosion_score_jump', 'Explosion Score Jump')], db_index=True, max_length=40),
        ),
    ]
